spring:
  profiles:
    active: prod  # dev, prod

app:
  name: MySpringApp
  version: 1.0.0
  server:
    port: 8080
    url: https://example.com
    timeout: 5000
  admins:
    - admin1@example.com
    - admin2@example.com
  metadata:
    region: korea
    owner: admin-team
