spring:
  application:
    name: 01_spring_strart

logging:
  level:
    root: info

server:
  tomcat:
    basedir: .
    access log:
      enabled: true
      directory: logs
      pattern: '%a %l %u %t "%r" %s %b'
      prefix: access_log
      suffix: .log
      rotate: true